### ISSUE TITLE
InternalServerErrorException (class not found)

### ISSUE THREAD

**Issue by nmoreaud** [ofpinewood/http-exceptions#75]
Hello,

Thanks for your library.
At the end of the documentation, some HTTP error codes are listed, however it seems that only part of the are implemented.
Could you add the other ones ?

**Comment by petervandenhout** [comment]
@nmoreaud I have not kept the docs up-to-date, because the `InternalServerErrorException` has been made into the base `HttpException` class. It has been updated now..

You can create your own HttpExceptions by inheriting from the `HttpExceptionBase` class. For instance to create a `NotAcceptableException` (406).

``` csharp
public class NotAcceptableException : HttpExceptionBase
{
    public override HttpStatusCode StatusCode { get; protected set; } = HttpStatusCode.NotAcceptable;

    public override string HelpLink { get; set; } = ResponseStatusCodeLink.NotAcceptable;

    public NotAcceptableException(string message) : base(message) { }
}

throw new new NotAcceptableException("Totally unacceptable!");
```

**Comment by petervandenhout** [comment]
@nmoreaud does this explain / solve your issue?

**Comment by petervandenhout** [comment]
@nmoreaud does this explain / solve your issue?
