### ISSUE TITLE
This project looks... familiar?

### ISSUE THREAD

**Issue by khellang** [ofpinewood/http-exceptions#77]
Hi @petervandenhout! 👋🏻 

I just stumbled across this project and couldn't help but notice it's _extremely_ similar to [my ProblemDetails middleware](https://github.com/khellang/Middleware) which has been around since 2017 and has ~1.5M downloads on [NuGet](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails) 😅 

Browsing through a couple of commits, I can see lots of references to my middleware and a lot of code that seems to have been blatantly copied, only to be slightly modified, but I can't see any attribution or mentions anywhere. Even some of my comments was copied 🙈 Was this intentional?

Ripping off someone's project and not leaving any form of attribution [as required by the MIT license](https://github.com/khellang/Middleware/blob/master/LICENSE) is bad form and not how OSS works 😞 

Some offending commits:
https://github.com/ofpinewood/http-exceptions/commit/2cbfc55db14796dbb26116d21a4aa4f7d72dc562
https://github.com/ofpinewood/http-exceptions/commit/1ec41e07b2751d7a638aa0c1c3a14b6127246dd1
https://github.com/ofpinewood/http-exceptions/commit/64dcea8e80a64b9402aca60245087c8290ad3c3f

**Comment by PureKrome** [comment]
/me subscribed to this thread. 

![](https://media.giphy.com/media/2uwZ4xi75JhxZYeyQB/giphy.gif)

**Comment by petervandenhout** [comment]
Hi @khellang 

This project started out as a internal way of throwing errors from an api, at the startup I was at on 2016. Back then it was a bit simpler. After moving to the next startup I've implemented the same thing again and updated it a bit for the then new problem details in aspnetcore. Then some time later I decided that this would be a good OSS project and I've added it to github. I'm still using this project for some private project I'm maintaining.

And while coding this project I found your project as well. And I borrowed some things from it, because back then I was still learning on how to do some of the netcore middleware things. This was also my first OSS project that I've put onto github, well the first that wasn't just some "hello world", so forgive me my mistakes in not using the correct form. 
But since the roots of this project lie in 2016, and I've only borrowed some middleware ideas, I dont see this as ripping of your project. It is more like copying some code from stackoverflow. 

I will add some mention/attribution to you in the code, because that seems fair though.

**Comment by khellang** [comment]
> it is more like copying some code from stack overflow

You know that code posted on StackOverflow is licensed under [CC BY-SA 3.0/4.0](https://creativecommons.org/licenses/by-sa/4.0/] (depending on the time of posting) and requires attribution when copied as well, right?

When copying or writing code code "heavily influenced by" other people's work, I think it's only fair to give some attribution, or at least mention it somewhere. Especially when that code has a license that requires it 😅

**Comment by petervandenhout** [comment]
I've added a [NOTICE.md](https://github.com/ofpinewood/http-exceptions/blob/main/NOTICE.md)

**Comment by khellang** [comment]
That's great. Thanks! 😘

**Comment by petervandenhout** [comment]
@khellang you're welcome. I'm still learning on how to do OSS, so today I've learned something new that I'll take into account for future stuff.

**Comment by mattjohnsonpint** [comment]
Thanks for giving Kristian credit for his work.  That's all anyone really is looking for with this stuff anyway (usually).

If you'd like an example of another project that acknowledges the work of others, have a look at one of mine:
https://github.com/mattjohnsonpint/GeoTimeZone

I use both an Acknowledgements section in the Readme file, and reference the original author's licenses in my license file.
